%YAML:1.0
#common parameters
imu_topic: "/mynteye/imu/data_raw"
#image_topic: "/mynteye/left/image_raw"
image_topic: "/mynteye/left_rect/image_rect"
output_path: "/home/shu/catkin_ws/src/VINS-Mono/output/"

use_mynteye_adapter: 1
mynteye_imu_srv: "s1"

#camera calibration, please replace it with your own calibration file.
#kalib
model_type: PINHOLE
camera_name: camera
image_width: 752
image_height: 480
distortion_parameters:
   k1: -0.2988636148524402
   k2: 0.08221871188076091
   p1: 0.00047748414598133604
   p2: -0.00011392533841534008
projection_parameters:
   fx: 439.12472698845284
   fy: 439.65762370518974
   cx: 356.94016689742233
   cy: 231.07744714937556

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0    # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        
#If you choose 0 or 1, you should write down the following matrix.

#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   # data: [-0.00323751, -0.99997598, -0.00612781,
   #         0.99977854, -0.00336417,  0.02077387, 
   #         -0.02079398, -0.0060592 ,  0.99976542]
   data: [-0.00385434, -0.99999075,  0.00190993,
          0.9999665,  -0.00384044,  0.00722804,
          -0.00722064,  0.00193773,  0.99997205]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   # data: [0.00036127, -0.04229565, 0.02348288]
   data: [0.00189856, -0.04274613, 0.02148916]

#feature traker paprameters
max_cnt: 400  #150          # max feature number in feature tracking
min_dist: 20  #30         # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.025227447575988642          # accelerometer measurement noise standard deviation. #0.599298904976
gyr_n: 0.0008260627013244607        # gyroscope measurement noise standard deviation.     #0.198614898699
acc_w: 0.0014408770311830344         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 2.377076607025522e-05       # gyroscope bias random work noise standard deviation.     #4.0e-5

#imu parameters       The more accurate parameters you provide, the better performance
#acc_n: 7.6509e-02           # accelerometer measurement noise standard deviation. #0.599298904976
#gyr_n: 9.0086e-03          # gyroscope measurement noise standard deviation.     #0.198614898699
#acc_w: 5.3271e-02        # accelerometer bias random work noise standard deviation.  #0.02
#gyr_w: 5.5379e-05        # gyroscope bias random work noise standard deviation.     #4.0e-5

g_norm: 9.8063822 #9.81007     # gravity magnitude

#loop closure parameters
loop_closure: 1                    # start loop closure
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 1             # useful in real-time and large project
pose_graph_save_path: "/home/shu/catkin_ws/src/VINS-Mono/pose_graph/TEST/" # save and load path

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: 0.006964262919379323            # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet). 

#visualization parameters
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ

